get_diet_recommendation = {
    'Fungal infection': ['Garlic', 'Yogurt', 'Turmeric', 'Neem', 'Coconut Oil'],
    'Allergy': ['Turmeric', 'Honey', 'Green Tea', 'Ginger', 'Omega-3 Rich Foods'],
    'GERD': ['Oatmeal', 'Ginger Tea', 'Leafy Greens', 'Banana', 'Almond Milk'],
    'Chronic cholestasis': ['Beetroot', 'Carrots', 'Papaya', 'Spinach', 'Turmeric'],
    'Drug Reaction': ['Aloe Vera', 'Coconut Water', 'Mint Leaves', 'Cucumber', 'Banana'],
    'Peptic ulcer disease': ['Cabbage Juice', 'Bananas', 'Oatmeal', 'Yogurt', 'Honey'],
    'AIDS': ['Protein-Rich Foods', 'Fruits', 'Vegetables', 'Whole Grains', 'Nuts and Seeds'],
    'Diabetes': ['Bitter Gourd', 'Fenugreek Seeds', 'Indian Gooseberry', 'Turmeric', 'Cinnamon'],
    'Gastroenteritis': ['Banana', 'Boiled Potatoes', 'Yogurt', 'Ginger Tea', 'White Rice'],
    'Bronchial Asthma': ['Garlic', 'Turmeric', 'Ginger', 'Mustard Oil', 'Honey'],
    'Hypertension': ['Banana', 'Leafy Greens', 'Oats', 'Berries', 'Garlic'],
    'Migraine': ['Ginger Tea', 'Peppermint Tea', 'Dark Chocolate', 'Salmon', 'Almonds'],
    'Cervical spondylosis': ['Carrot Juice', 'Turmeric', 'Garlic', 'Leafy Greens', 'Ginger Tea'],
    'Paralysis (brain hemorrhage)': ['Blueberries', 'Walnuts', 'Salmon', 'Spinach', 'Green Tea'],
    'Jaundice': ['Lemon Juice', 'Papaya', 'Bottle Gourd Juice', 'Beetroot', 'Radish'],
    'Malaria': ['Cinnamon Tea', 'Ginger Tea', 'Orange Juice', 'Papaya', 'Coconut Water'],
    'Chicken pox': ['Oatmeal Bath', 'Neem Leaves', 'Baking Soda', 'Green Tea', 'Honey'],
    'Dengue': ['Papaya Leaf Juice', 'Coconut Water', 'Broth Soups', 'Porridge', 'Herbal Tea'],
    'Typhoid': ['Banana', 'Plain Rice', 'Applesauce', 'Boiled Potatoes', 'Ginger Tea'],
    'Hepatitis A': ['Turmeric', 'Garlic', 'Leafy Greens', 'Beetroot', 'Carrot Juice'],
    'Hepatitis B': ['Garlic', 'Leafy Greens', 'Carrot Juice', 'Turmeric', 'Ginger Tea'],
    'Hepatitis C': ['Turmeric', 'Garlic', 'Leafy Greens', 'Beetroot', 'Carrot Juice'],
    'Hepatitis D': ['Garlic', 'Leafy Greens', 'Carrot Juice', 'Turmeric', 'Ginger Tea'],
    'Hepatitis E': ['Turmeric', 'Garlic', 'Leafy Greens', 'Beetroot', 'Carrot Juice'],
    'Alcoholic hepatitis': ['Turmeric', 'Ginger Tea', 'Leafy Greens', 'Garlic', 'Beetroot'],
    'Tuberculosis': ['Turmeric', 'Garlic', 'Leafy Greens', 'Ginger Tea', 'Cayenne Pepper'],
    'Common Cold': ['Ginger Tea', 'Chicken Soup', 'Honey', 'Citrus Fruits', 'Garlic'],
    'Pneumonia': ['Garlic', 'Ginger Tea', 'Honey', 'Turmeric', 'Oregano Tea'],
    'Dimorphic hemorrhoids (piles)': ['Fiber-Rich Foods', 'Fluids', 'Green Leafy Vegetables', 'Whole Grains', 'Prunes'],
    'Heart attack': ['Oats', 'Olive Oil', 'Garlic', 'Leafy Greens', 'Berries'],
    'Varicose veins': ['Flaxseeds', 'Ginger', 'Cayenne Pepper', 'Leafy Greens', 'Berries'],
    'Hypothyroidism': ['Seaweed', 'Brazil Nuts', 'Turmeric', 'Ginger', 'Coconut Oil'],
    'Hyperthyroidism': ['Cruciferous Vegetables', 'Yogurt', 'Berries', 'Whole Grains', 'Nuts'],
    'Hypoglycemia': ['Sweet Potatoes', 'Oats', 'Nuts', 'Berries', 'Cinnamon'],
    'Osteoarthritis': ['Turmeric', 'Ginger Tea', 'Leafy Greens', 'Fatty Fish', 'Berries'],
    'Arthritis': ['Ginger', 'Turmeric', 'Berries', 'Pineapple', 'Walnuts'],
    'Vertigo (Paroxysmal Positional Vertigo)': ['Ginger Tea', 'Ginkgo Biloba', 'Almonds', 'Spinach', 'Salmon'],
    'Acne': ['Green Tea', 'Turmeric', 'Fruits', 'Vegetables', 'Nuts'],
    'Urinary tract infection': ['Cranberry Juice', 'Watermelon', 'Yogurt', 'Celery', 'Cucumber'],
    'Psoriasis': ['Turmeric', 'Olive Oil', 'Leafy Greens', 'Fish', 'Nuts'],
    'Impetigo': ['Turmeric', 'Honey', 'Neem Leaves', 'Coconut Oil', 'Aloe Vera Gel']
}

print(get_diet_recommendation["AIDS"])
